# Generated by Django 5.1.3 on 2024-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_description_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
