# Generated by Django 5.1.3 on 2024-12-23 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='time',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.AddField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('BREAKDOWN', 'Breakdown'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_time',
            field=models.IntegerField(blank=True, help_text='Resolution time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='routes.route'),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='route',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='routes.route'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RouteChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('VEHICLE', 'Vehicle Change'), ('STAFF', 'Staff Change')], max_length=20)),
                ('change_date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('late_pickup_minutes', models.IntegerField(default=0)),
                ('timely_pickup', models.BooleanField(default=True)),
                ('late_school_pickup_minutes', models.IntegerField(default=0)),
                ('late_dropoff_minutes', models.IntegerField(default=0)),
                ('timely_dropoff', models.BooleanField(default=True)),
                ('late_school_dropoff_minutes', models.IntegerField(default=0)),
                ('late_home_pickup', models.BooleanField(default=False)),
                ('late_home_dropoff', models.BooleanField(default=False)),
                ('timely_home_pickup', models.BooleanField(default=True)),
                ('timely_home_dropoff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='routes.route')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='routes_rout_date_95d6b8_idx'), models.Index(fields=['route', 'date'], name='routes_rout_route_i_1f4ed3_idx')],
            },
        ),
    ]
