# Generated by Django 5.1.3 on 2024-12-24 02:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_school_remove_incident_severity_remove_incident_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='actual_duration',
            field=models.DurationField(blank=True, help_text='Actual duration of the route', null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='planned_duration',
            field=models.DurationField(blank=True, help_text='Planned duration of the route', null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='schedule_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='RouteCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_on_time', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='routes.route')),
            ],
        ),
    ]
